apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: epjn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-hdgs-tenant/byoc-app-hwng/epjn@sha256:046f7ed6e2382e73284044c36e10e563b9c6146b7f6a1ab48a4b0db0d4ff42dd
        name: my-java-quarkus
        resources: {}
status: {}
