apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: epjn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: epjn
    app.kubernetes.io/part-of: byoc-app-hwng
  name: epjn
spec:
  rules:
  - host: epjn-byoc-hdgs-tenant.apps.d776927a8ed315a21abc.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: epjn
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
