apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: epjn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: epjn
    app.kubernetes.io/part-of: byoc-app-hwng
  name: epjn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: epjn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: epjn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-hdgs-tenant/byoc-app-hwng/epjn@sha256:046f7ed6e2382e73284044c36e10e563b9c6146b7f6a1ab48a4b0db0d4ff42dd
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
